### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by levjj** [davidk01/typescript-parser-combinators#1]
This is a really great project! Is the code available under an open source license, so I can use it in my projects? Ideally, you could use something like an ISC, MIT or BSD license.

**Comment by davidk01** [comment]
Thanks. MIT looks good. I'll add it shortly.

**Comment by davidk01** [comment]
Done: e527f6037c319628502f78cbff3b2fa2700a6d1f

**Comment by levjj** [comment]
Wow, that was quick. Thanks!
