### ISSUE TITLE
Base parsers

### ISSUE THREAD

**Issue by jupvfranco** [davidk01/typescript-parser-combinators#2]
Nice work!
I have a question though. 
> In fact the elements of the input stream do not have to be characters so the full generality comes into effect when you start parsing things like ['abc', 'def', 'hij']

Actually, I'm trying to parse something like that and it's not working. 
These are my parsers
```
  static trueKW: Parser = Parser.m(x => x === 'true'); 
  static falseKW: Parser = Parser.m(x => x === 'false'); 
```

Very similar to the ones in the readme file. It seems that it is only matching char by char. Any simple way of checking the whole word?

**Comment by davidk01** [comment]
Hi. Can you show me the input you are trying to parse? I created a test to make sure I understood what you were asking and if I interpreted your question correctly things should work as explained in the example.

Here is my test program

```typescript
/// <reference path="./combinators.ts"/>
class T {
  static t = Parser.m(x => x === 'true');
  static f = Parser.m(x => x === 'false');
}
let tSuccess = T.t.parse_input(['true']);
let fSuccess = T.f.parse_input(['false']);
let tFailure = T.t.parse_input(['false']);
let fFailure = T.f.parse_input(['true']);
console.log(tSuccess);
console.log(fSuccess);
console.log(tFailure);
console.log(fFailure);
```

When I compile and run it I get the following output which is what I expect

```bash
$ tsc combinators.ts test.ts --outFile test.js
$ node test.js
true
false
null
null
```

Let me know if that helps.

**Comment by jupvfranco** [comment]
yes, that's helpful. Thank you. 
I was not using square brackets.

**Comment by davidk01** [comment]
You are welcome. Happy coding.
